# NOTE: https://starship.rs/config
# ln -s ~/.zsh/starship.toml ~/.config/starship.toml

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = "$time$all$kubernetes$line_break$character"
command_timeout = 2000

[aws]
# disabled = true
symbol = '󰸏 '

[python]
symbol = '󰌠 '

[golang]
symbol = '󰟓 '

[ruby]
symbol = '󰴭 '

[time]
disabled = false
format = "[$time]($style) | "

[terraform]
format = 'via [$symbol($version )]($style) '
symbol = '󱁢 '
detect_files = ['.tf']

[character]
# success_symbol = '[➜](bold green) '
# error_symbol = '[➜](bold red) '
# error_symbol = '󰯆 '

[kubernetes]
format = '[$symbol $context(\($namespace\))]($style) '
detect_files = ['kustomization.yaml']
symbol = '󱃾 '
contexts = [
  { context_pattern = ".*dev.*", style = "green"}, #, symbol = "⬢ " },
  { context_pattern = ".*prod.*", style = "red"} #, symbol = "⬢ " },
]

[git_branch]
symbol = '󰊤 '

[git_commit]
tag_symbol = ' 󰓹 '
only_detached = false
tag_disabled = false

[package]
disabled = true

[directory]
truncate_to_repo = false
truncation_length = 6
read_only = ' 🔒'

[nodejs]
detect_extensions = []
symbol = '󰎙 '

# TODO: not working
[hostname]
aliases = { "NL-GKWV0JNX2X" = "PTI" }
